name: Build PHP 8.3.8 extension_xdebug
on:
  workflow_dispatch:
jobs:
  get-extension-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the extension matrix
        id: extension-matrix
        uses: php/php-windows-builder/extension-matrix@v1
        with:
          extension-url: https://github.com/xdebug/xdebug
          extension-ref: '3.3.1'
          php-version-list: '8.3.8'
          arch-list: 'x64'
          ts-list: 'ts'
