name: Build PHP 8.3.8 extension_sqlite3
on:
  workflow_dispatch:
jobs:
  php:
    strategy:
      matrix:
        arch: [x64]
        ts: [ts]
    runs-on: windows-2019
    steps:
      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          extension-url: https://github.com/xdebug/xdebug
          extension-ref: '3.3.1'
          php-version: '8.3'
          ts: 'ts'
          arch: 'x64'
          args: '--enable-xdebug'
          
