name: Build PHP 8.3.8 extension_sqlite3
on:
  workflow_dispatch:
jobs:
  php:
    strategy:
      matrix:
        arch: [x64]
        ts: [ts]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          php-version: '8.3.8' 
          extension-url: https://github.com/sqlite/sqlite
          extension-ref: '3.47.0'
          php-version-list: '8.3'
          arch-list: 'x64'
          ts-list: 'ts'
          args: '--enable-sqlite3-rtree'
          libs: 'zlib'
